services:
    jbreu.groupsonregistration.listener:
        class: jbreu\groupsonregistration\event\load_groups_listener
        arguments:
            - '@template'
            - '@dbal.conn'
            - '@request'
            - '@user'
        tags:
            - { name: event.listener }
